### ISSUE TITLE
Works only on Linux

### ISSUE THREAD

**Issue by kbzowski** [jwhitbeck/gmail-archive#1]
App depends on xdg-open and does not work on Windows.

> events.js:186
      throw er; // Unhandled 'error' event
      ^
Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [
    'https://accounts.google.com/o/oauth2/v2/auth [...]'
  ]

**Comment by jwhitbeck** [comment]
Hi,

Thanks for reporting this issue. I don't have a Windows system, so I'm unsure what the Windows approach should be. 

I'd be happy to review a PR though.
